In [1]:
import numpy as np

In [2]:
l=[2,3,4,5,6,7,8,3.5]
ar=np.array(l)
print(ar.ndim)
print(ar)

1
[2.  3.  4.  5.  6.  7.  8.  3.5]


In [3]:
data=np.arange(1,20,2)
data

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [4]:
r=np.random.randn(3,3,3)
r

array([[[-1.28044398,  0.71181783,  0.43545377],
        [-1.28809801,  0.80382853, -0.53003097],
        [ 1.23664517,  1.818391  ,  2.17483136]],

       [[-0.94797337, -0.95346269,  2.83848017],
        [-1.28291503, -0.11393048,  1.49183763],
        [-0.1505734 , -0.34366592, -1.3301167 ]],

       [[-1.05217051,  0.39964436, -0.61695537],
        [ 0.71738181, -1.09151446, -0.30269611],
        [-1.91681394, -0.40928817,  1.51614606]]])

In [5]:
r+5

array([[[3.71955602, 5.71181783, 5.43545377],
        [3.71190199, 5.80382853, 4.46996903],
        [6.23664517, 6.818391  , 7.17483136]],

       [[4.05202663, 4.04653731, 7.83848017],
        [3.71708497, 4.88606952, 6.49183763],
        [4.8494266 , 4.65633408, 3.6698833 ]],

       [[3.94782949, 5.39964436, 4.38304463],
        [5.71738181, 3.90848554, 4.69730389],
        [3.08318606, 4.59071183, 6.51614606]]])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.empty((2,2,2))

array([[[2. , 3. ],
        [4. , 5. ]],

       [[6. , 7. ],
        [8. , 3.5]]])

In [9]:
r1=np.array((2,3,4,5,6,4.6),dtype=int)

In [10]:
r1

array([2, 3, 4, 5, 6, 4])

In [11]:
r1.dtype

dtype('int32')

In [12]:
r2=np.arange((200),dtype=float)

In [13]:
r2

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [14]:
r2=np.array([3,4,5,6,7])

In [15]:
r2.dtype

dtype('int32')

In [16]:
r3=r2.astype(float)
r2

array([3, 4, 5, 6, 7])

In [17]:
r3

array([3., 4., 5., 6., 7.])

In [18]:
r2

array([3, 4, 5, 6, 7])

In [19]:
ar=np.array([[2,3,4,5],[4,6,7,8]])
ar

array([[2, 3, 4, 5],
       [4, 6, 7, 8]])

In [20]:
ar+ar

array([[ 4,  6,  8, 10],
       [ 8, 12, 14, 16]])

In [21]:
ar*ar

array([[ 4,  9, 16, 25],
       [16, 36, 49, 64]])

In [22]:
ar-ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
ar=np.arange(27).reshape(3,3,3)
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
ar2d=np.array([[12,3,4,5],[3,67,54,32],[67,76,90,87]])
ar2d

array([[12,  3,  4,  5],
       [ 3, 67, 54, 32],
       [67, 76, 90, 87]])

In [25]:
ar2d[0][1]

3

In [26]:
ar2d[1,3]

32

In [27]:
oldv=ar2d[0,0].copy()

In [28]:
ar2d

array([[12,  3,  4,  5],
       [ 3, 67, 54, 32],
       [67, 76, 90, 87]])

In [29]:
ar2d

array([[12,  3,  4,  5],
       [ 3, 67, 54, 32],
       [67, 76, 90, 87]])

In [30]:
ar=np.arange(27).reshape(3,3,3)

In [31]:
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
ar[2,1,1]

22

In [33]:
data = np.random.randn(7, 4)

In [34]:
data

array([[ 0.3070211 ,  0.77473067,  0.64571381,  0.08640413],
       [-0.45944154,  0.57616908, -0.54709777, -0.59906045],
       [-1.94843603,  1.0743326 ,  0.0411364 , -0.52965046],
       [ 0.21996358,  0.28333456,  1.60941569, -1.40384126],
       [-0.0400078 ,  0.03693992, -0.16885369,  0.22450842],
       [ 0.93893815,  1.4574932 ,  0.31196298,  2.07436692],
       [ 1.31347095, -0.32955134, -0.51650816, -1.26270385]])

In [35]:
name=np.array(["mahaz","abbasi","mahaz","adeel","ahmed","assd","effd"])

In [36]:
name

array(['mahaz', 'abbasi', 'mahaz', 'adeel', 'ahmed', 'assd', 'effd'],
      dtype='<U6')

In [37]:
name=="mahaz"

array([ True, False,  True, False, False, False, False])

In [38]:
data[name=="mahaz"]

array([[ 0.3070211 ,  0.77473067,  0.64571381,  0.08640413],
       [-1.94843603,  1.0743326 ,  0.0411364 , -0.52965046]])

In [39]:
data

array([[ 0.3070211 ,  0.77473067,  0.64571381,  0.08640413],
       [-0.45944154,  0.57616908, -0.54709777, -0.59906045],
       [-1.94843603,  1.0743326 ,  0.0411364 , -0.52965046],
       [ 0.21996358,  0.28333456,  1.60941569, -1.40384126],
       [-0.0400078 ,  0.03693992, -0.16885369,  0.22450842],
       [ 0.93893815,  1.4574932 ,  0.31196298,  2.07436692],
       [ 1.31347095, -0.32955134, -0.51650816, -1.26270385]])

In [40]:
data[data>0]=1

In [41]:
data

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [-0.45944154,  1.        , -0.54709777, -0.59906045],
       [-1.94843603,  1.        ,  1.        , -0.52965046],
       [ 1.        ,  1.        ,  1.        , -1.40384126],
       [-0.0400078 ,  1.        , -0.16885369,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        , -0.32955134, -0.51650816, -1.26270385]])

# fancing indexing

In [42]:
ar=np.empty((8,4))

In [43]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
for i in range(8):
    ar[i]=i

In [45]:
ar

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [46]:
ar[[-1,-3,-8]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.]])

In [114]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [119]:
arr[[1,0],[0,1]]

array([4, 1])

# Transposing Arrays and Swapping Axes

In [128]:
ar=np.arange(15).reshape(5,3)
ar

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [127]:
ar.shape

(5, 3)

In [126]:
a=ar.T
a.shape

(3, 5)

In [129]:
a

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [130]:
a.T

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [132]:
ar=np.arange(16).reshape((2,2,4))

In [133]:
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [138]:
ar.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [58]:
ar.transpose(2,1,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [59]:
ar.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [60]:
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
ar=np.arange(16).reshape((2,2,4))
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [62]:
ar=np.arange(10)

In [63]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [66]:
ar=np.random.randn(8)
ar

array([-1.83176822, -0.12450202, -3.28767225,  1.0372548 ,  0.33407341,
        0.19655803, -0.29606885,  0.73983601])

In [67]:
arr=np.random.randn(8)
arr

array([0.20091874, 0.55546345, 1.25623207, 1.883305  , 0.36373364,
       0.49296436, 0.13512976, 0.33218043])

In [68]:
np.maximum(ar,arr)

array([0.20091874, 0.55546345, 1.25623207, 1.883305  , 0.36373364,
       0.49296436, 0.13512976, 0.73983601])

In [69]:
ar=np.random.randn(8)+10
ar

array([ 9.70983712,  8.33268021,  9.51667907, 10.74679261,  9.49526206,
        8.65140011, 10.17277892, 11.33450899])

In [70]:
remainder, whole_part = np.modf(ar)

In [71]:
remainder

array([0.70983712, 0.33268021, 0.51667907, 0.74679261, 0.49526206,
       0.65140011, 0.17277892, 0.33450899])

In [72]:
whole_part

array([ 9.,  8.,  9., 10.,  9.,  8., 10., 11.])

In [73]:
arr

array([0.20091874, 0.55546345, 1.25623207, 1.883305  , 0.36373364,
       0.49296436, 0.13512976, 0.33218043])

In [74]:
np.sqrt(arr)

array([0.4482396 , 0.7452942 , 1.12081759, 1.3723356 , 0.60310334,
       0.70211421, 0.3676    , 0.57635096])

In [75]:
np.sqrt(ar,arr)

array([3.11606115, 2.88663822, 3.08491152, 3.2782301 , 3.08143831,
       2.94132625, 3.18947941, 3.36667625])

In [76]:
ar

array([ 9.70983712,  8.33268021,  9.51667907, 10.74679261,  9.49526206,
        8.65140011, 10.17277892, 11.33450899])

In [77]:
arr

array([3.11606115, 2.88663822, 3.08491152, 3.2782301 , 3.08143831,
       2.94132625, 3.18947941, 3.36667625])

In [78]:
np.full((3,3,3),7)

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [79]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
np.identity??

In [81]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [82]:
np.ceil(4.57)

5.0

In [83]:
np.floor(4.57)

4.0

In [84]:
a=(6,7,7,8,9)
b=(4,5,6,7,8)
np.setxor1d(a,b)

array([4, 5, 9])

In [85]:
ar=np.arange(9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
np.save("my array",ar)

In [87]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
np.load("my array.npy")

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
a=np.arange(1,7)
b=a+2
print(a,b, sep="\n")

[1 2 3 4 5 6]
[3 4 5 6 7 8]


In [90]:
np.stack((a,b))

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]])

In [91]:
np.stack((a,b),axis=1)

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6],
       [5, 7],
       [6, 8]])

In [92]:
np.column_stack((a,b))

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6],
       [5, 7],
       [6, 8]])

In [93]:
print(np.stack((a,b),axis=0))
print(np.row_stack((a,b)))

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]


In [94]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7, 8])

In [95]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]])

In [96]:
np.block([a,b])

array([1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7, 8])

In [97]:
a=np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [98]:
np.split(a,3)

[array([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]]), array([[[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]), array([[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])]

In [99]:
b=np.arange(36).reshape(6,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [100]:
np.split(b,2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [101]:
a=np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
np.dsplit(a,2)

[array([[[0],
         [2]],
 
        [[4],
         [6]]]), array([[[1],
         [3]],
 
        [[5],
         [7]]])]

In [103]:
a=np.random.randint(1,10, size=(3,3))
a+5

array([[13, 12, 13],
       [11, 10,  7],
       [12, 14, 10]])

In [104]:
b=np.full_like(a,5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [105]:
c=np.random.randint(1,10,size=20)
c

array([1, 8, 1, 1, 5, 9, 9, 5, 4, 5, 4, 4, 4, 7, 4, 8, 2, 9, 5, 2])

In [106]:
np.unique(c)

array([1, 2, 4, 5, 7, 8, 9])

In [107]:
a=np.random.randint(1,10,size=(5))
b=np.random.randint(1,10,size=(10))
print(a,b, sep="\n")

[True if x in a else False for x in b]

[1 5 7 1 6]
[4 9 6 2 6 8 5 9 8 6]


[False, False, True, False, True, False, True, False, False, True]

In [108]:
np.in1d(b,a)

array([False, False,  True, False,  True, False,  True, False, False,
        True])